summary: "Batch list"
description: "Displays list of batches allocated to user"
# security:
#   - cookieAuth:
#     type: apiKey
#     in: cookie
#     name: session
parameters:
- in: path
  name: userId
  # description: "Accepts dictionary having email and password values"
  required: true
  schema:
    type: string
responses:
  200:
    description: "Login Successful"
#   401:
#     description: "Invalid credentials"